### ISSUE TITLE
关于AbemaTV出现【该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试】的问题

### ISSUE THREAD

**Issue by XSky123** [Last-Order/Minyami-chrome-extension#1]
插件版本1.0.11
浏览器 Chrome 71.0.3578.98

直接在Abema直播页面打开，比如https://abema.tv/now-on-air/abema-anime-2
插件显示【该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试】
请问是就是不支持Abema的直播还是我设置的问题，谢谢。

**Comment by Last-Order** [comment]
该频道不支持（是MPEG-DASH）
