### ISSUE TITLE
bilibili直播有时获取标题信息会失败

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Minyami-chrome-extension#22]
![image](https://user-images.githubusercontent.com/5925733/108665364-b796ba80-750f-11eb-951c-6df845ddb7e7.png)

其实主要问题是容易造成不仔细看无脑下载的时候文件互相覆盖。

**Comment by Last-Order** [comment]
改了下，优先从 SSR 信息里取，取不到使用`document.title`。
