### ISSUE TITLE
Chrome plugin can't get key on Nogidoga.com

### ISSUE THREAD

**Issue by DCxDESIGN** [Last-Order/Minyami-chrome-extension#24]
There might be an update applied on nogidoga.com after February 20th, and since then, Chrome plugin of Minyami can no longer get the key (or precisely, no entry displayed in the plugin? just like in YouTube) when viewing video playback page on this site.

**Comment by Last-Order** [comment]
It should be fixed in 1.0.31. Please have a try.

**Comment by DCxDESIGN** [comment]
> It should be fixed in 1.1.31. Please have a try.

It works now, thank you so much!
