### ISSUE TITLE
TwitCasting録画下載參數

### ISSUE THREAD

**Issue by JesseTu75** [Last-Order/Minyami-chrome-extension#29]
TC從ライブ履歴下載録画時須帶Headers：Origin、Host、User-Agent（需與瀏覽器發出的要求header相同）
且在預設5個thread的情況下會被服務器屏蔽
目前測試3個thread可以正常運行
是否能在提取時加上上述header與thread數量限制

**Comment by Last-Order** [comment]
给个视频链接？

**Comment by JesseTu75** [comment]
https://twitcasting.tv/_gocchan_/movie/699312538

**Comment by Last-Order** [comment]
1.3.4加上了

**Comment by JesseTu75** [comment]
今天測試發現有些分塊太小的視頻(200-300KB)
儘管設置 `--threads 1` 也有可能因為請求速度太快而被屏蔽
(e.g. https://twitcasting.tv/kbtntn/movie/658228550 )
可能需要有類似kkr的 `--cooldown` 參數才能解決
