### ISSUE TITLE
niconico会限时光机无法抓取

### ISSUE THREAD

**Issue by momo-s07** [Last-Order/Minyami-chrome-extension#33]
插件版本：1.3.6
浏览器：Microsoft Edge 7.0.1072.62
该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试

**Comment by Last-Order** [comment]
请提供视频链接

**Comment by momo-s07** [comment]
> 请提供视频链接

https://live.nicovideo.jp/watch/lv335164067

**Comment by momo-s07** [comment]
> 请提供视频链接

https://live.nicovideo.jp/watch/lv335164046
这个开头15分钟免费的可以抓取但我没试，不知道下载的是不是完整的

**Comment by Last-Order** [comment]
未能复现，是否尝试过重新安装浏览器扩展？

**Comment by momo-s07** [comment]
> 未能复现，是否尝试过重新安装浏览器扩展？

重装之后好了.....
可是我前几天都正常抓取，难道是插件bug？

**Comment by Last-Order** [comment]
可能是 但我也不知道为啥 总之下次可以先试下重装
