### ISSUE TITLE
关于 のぎ動画 的站点支持

### ISSUE THREAD

**Issue by DCxDESIGN** [Last-Order/Minyami-chrome-extension#39]
![image](https://user-images.githubusercontent.com/48208459/157849247-91d9b7c3-a7bb-419d-8093-52dc37a750aa.png)

您好，如图所示，现版本下会提示缺少 key（刷新或者新开标签也是一样的），但将地址全选复制也可以正常使用；而老版本没有这项提示，也一直使用正常

![image](https://user-images.githubusercontent.com/48208459/157849703-c152c109-1f20-4bbf-9ac5-2f0655201836.png)

可能是哪里的判定条件出了点小问题？

**Comment by Last-Order** [comment]
也就是说 nogidoga 现在不需要 key 就能下载对吗

**Comment by DCxDESIGN** [comment]
> 也就是说 nogidoga 现在不需要 key 就能下载对吗

抱歉我不是很清楚 key 具体指什么，是指前面图里地址中的 token 部分吗。。
如果是的话，之前是能读的，现在也能读，所以显示缺少 key 可能只是显示错误；
如果不是指这个 token 部分的话，那之前没有读也可以用，现在读不出来也可以用

**Comment by DCxDESIGN** [comment]
我翻了下我今年以来的 PowerShell 命令记录，Abema 是有专门的 --key 部分，のぎ動画没有这个部分，所以老版本下应该就是不读的，可以正常使用

**Comment by Last-Order** [comment]
更新扩展试一下~

**Comment by DCxDESIGN** [comment]
> 更新扩展试一下~

看到代码更新了~

不过商店那边好像还没更新。。

**Comment by Last-Order** [comment]
@DCxDESIGN 已经过审了，可以尝试手动更新一下
![image](https://user-images.githubusercontent.com/3362825/158047385-700a7c7a-3e83-41c7-bc18-7ecdf8fe276f.png)

**Comment by DCxDESIGN** [comment]
> @DCxDESIGN 已经过审了，可以尝试手动更新一下 ![image](https://user-images.githubusercontent.com/3362825/158047385-700a7c7a-3e83-41c7-bc18-7ecdf8fe276f.png)

诶。。我这里看商店还是 1.4.1 ，检查更新也没反应。。

![image](https://user-images.githubusercontent.com/48208459/158071651-22d1ba6a-e03c-44fb-8d8e-d8a11771e23a.png)

**Comment by CL-Jeremy** [comment]
您好，我是 1.4.0 更新引入这段问题代码的贡献者。
作为非会员，我刚刚尝试在 https://nogidoga.com/about 匿名观看了这个页面上的示例视频，发现它明显是加密过的，符合通用的加密 key 格式。
<img width="1318" alt="Bildschirmfoto 2022-03-14 um 12 06 58" src="https://user-images.githubusercontent.com/1714243/158160138-c86f0722-b047-48a8-b48c-391597b1e478.png">
经过测试发现，这是一个较为特殊的情况：chunklist 中引用的 key 是完整链接，因此不必由浏览器扩展截获，而是可以交由 Minyami 主程序直接重新下载。这是我之前的疏忽，给您带来了麻烦，深感抱歉。
稍后我会提交 proper fix，祝好。

**Comment by DCxDESIGN** [comment]
> 您好，我是 1.4.0 更新引入这段问题代码的贡献者。 作为非会员，我刚刚尝试在 https://nogidoga.com/about 匿名观看了这个页面上的示例视频，发现它明显是加密过的，符合通用的加密 key 格式。 <img alt="Bildschirmfoto 2022-03-14 um 12 06 58" width="1318" src="https://user-images.githubusercontent.com/1714243/158160138-c86f0722-b047-48a8-b48c-391597b1e478.png"> 经过测试发现，这是一个较为特殊的情况：chunklist 中引用的 key 是完整链接，因此不必由浏览器扩展截获，而是可以交由 Minyami 主程序直接重新下载。这是我之前的疏忽，给您带来了麻烦，深感抱歉。 稍后我会提交 proper fix，祝好。

您太客气了。。也就是说实际上由扩展程序捕获的地址（即使不另外带上 key 部分）是可以直接（交给 minyami 主程序）使用的，那么也就不需要在扩展程序里提示缺少 key 了，是这样理解对吧

**Comment by CL-Jeremy** [comment]
@DCxDESIGN 正是这样。下图为测试（这里临时解开了 /about 页面的解析，原理一样，正式版不会包括这个页面）
<img width="1322" alt="Bildschirmfoto 2022-03-14 um 13 24 59" src="https://user-images.githubusercontent.com/1714243/158171877-1547090d-31e1-40eb-b734-ff2ec1e6c39b.png">
<img width="561" alt="Bildschirmfoto 2022-03-14 um 13 25 57" src="https://user-images.githubusercontent.com/1714243/158172070-c2c88a71-6529-4bd7-88ef-03027253dbc2.png">

**Comment by DCxDESIGN** [comment]
> @DCxDESIGN 正是这样。下图为测试（这里临时解开了 /about 页面的解析，原理一样，正式版不会包括这个页面） <img alt="Bildschirmfoto 2022-03-14 um 13 24 59" width="1322" src="https://user-images.githubusercontent.com/1714243/158171877-1547090d-31e1-40eb-b734-ff2ec1e6c39b.png"> <img alt="Bildschirmfoto 2022-03-14 um 13 25 57" width="561" src="https://user-images.githubusercontent.com/1714243/158172070-c2c88a71-6529-4bd7-88ef-03027253dbc2.png">

好的明白了，期待更新

**Comment by DCxDESIGN** [comment]
1.4.3 此问题已解决，感谢两位开发者
