### ISSUE TITLE
niconico的channel能够抓到地址，但是Fanclub抓不到

### ISSUE THREAD

**Issue by GiftSheep** [Last-Order/Minyami-chrome-extension#59]
先谢谢您的插件，我看到了老的issue，不知道这算不算问题，如果是以nicochannel开头的网址插件能抓到地址、key等等数据，但是像FC这种自定义开头的网址就抓不到，因为能找到m3u8的地址但因为没key没法通过下载，所以想问问minyami的扩展有没有方法抓到FC视频的KEY

**Comment by GiftSheep** [comment]
打个比方就是https://rizuna-official.com/video/smPZ6L6fK5XzMc3gLXVZuRRs，这样子的网址扩展无法识别，https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L以nicochannel无异常

**Comment by Last-Order** [comment]
minyami扩展并非支持所有网站，支持范围外的网站请自行抓取key
