### ISSUE TITLE
Extension好像不支持fresh.tv?

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami-chrome-extension#7]
在fresh.tv无法获取到任何数据

![image](https://user-images.githubusercontent.com/4130991/73543704-297bfd80-43fd-11ea-9114-b8578c95e383.png)

测试地址 https://freshlive.tv/kido-ibuki/276085 （需要会员，如果需要可以提供账号）

稍微看了下code似乎也没有相关的逻辑

**Comment by Last-Order** [comment]
多刷几次 代码注入太迟了的原因

**Comment by fireattack** [comment]
搞定了，直接打开这个网址或者F5刷新试了几十遍都不行，先切到别的视频再切回来就可以了……
